worker_processes 1;
events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  server {
    listen ${PORT};
    root /app/dist;
    index index.html;

    # Servir mascotte.html directement SANS redirection
    location = /mascotte.html {
      try_files /mascotte.html =404;
    }

    # SPA fallback — toutes les autres routes → index.html React
    location / {
      try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
  }
}
